name: send_money_app
description: "A Flutter app for sending money with a clean architecture approach."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  get_it: ^7.6.4
  dartz: ^0.10.1
  get: ^4.6.6
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/svg/
    - assets/fonts/
    - assets/fonts/inter/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-BoldItalic.ttf
          weight: 700
          style: italic

 
